/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Louisa
 */
public class Penilaian extends javax.swing.JFrame {

    /**
     * Creates new form Penilaian
     */
    public Penilaian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNilai = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldAbsen = new javax.swing.JTextField();
        jTextFieldMapel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Penilaian");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 20, 210, 50);

        jLabel2.setText("Absen");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 130, 80, 40);

        jLabel3.setText("Mapel");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 180, 80, 40);

        jLabel4.setText("Nilai");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 230, 80, 40);

        jLabel5.setText("Hasil:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 360, 80, 40);

        jTextFieldNilai.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jTextFieldNilai);
        jTextFieldNilai.setBounds(210, 230, 230, 40);

        jTextFieldNama.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNama);
        jTextFieldNama.setBounds(210, 80, 230, 40);

        jTextFieldAbsen.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jTextFieldAbsen);
        jTextFieldAbsen.setBounds(210, 130, 230, 40);

        jTextFieldMapel.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jTextFieldMapel);
        jTextFieldMapel.setBounds(210, 180, 230, 40);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 310, 90, 40);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setText("Proses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(80, 310, 90, 40);

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(230, 310, 90, 40);

        jLabel6.setText("Nama");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 80, 80, 40);

        jTextArea1.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 390, 390, 110);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 590, 530);

        setBounds(0, 0, 606, 573);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String nama = jTextFieldNama.getText();
        int absen = Integer.parseInt(jTextFieldAbsen.getText());
        String mapel = jTextFieldMapel.getText();
        int nilai = Integer.parseInt(jTextFieldNilai.getText());
        String predikat;
        if (nilai >= 86 && nilai <=100)
        {
            predikat = "Sempurna";
        }
        else if (nilai >= 75 && nilai <=85)
        {
            predikat = "Lulus";
        }
        else if (nilai >=0 && nilai <=74)
        {
            predikat = "Tidak Lulus";
        }
        else 
        {
            predikat = "Nilai yang anda masukkan tidak sesuai";
        }
        jTextArea1.setText("Nama Siswa: "+nama+"\n"+"Nomer Absen: "+absen+"\n"+"Mata Pelajaran: "+mapel+"\n"+"Predikat: "+predikat);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        jTextFieldNama.setText("");
        jTextFieldAbsen.setText("");
        jTextFieldMapel.setText("");
        jTextFieldNilai.setText("");
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penilaian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldAbsen;
    private javax.swing.JTextField jTextFieldMapel;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNilai;
    // End of variables declaration//GEN-END:variables
}
